=== Jose-ignacio-vazquez/lmsgiactividad2/biblioteca.dtd
<!ELEMENT biblioteca (libros+,revistas+,periodicos+)>
<!-- -->
<!ELEMENT libros (libro+)>
<!-- 
<!ELEMENT revistas (revista+)>
<!ELEMENT periodicos (periodico+)>
<!ELEMENT periodico (nacional | internacional)>
-->
<!ELEMENT libro (titulo,capitulo+,indice,sinopsis)>
    <!ATTLIST libro id ID #REQUIRED>
    <!ATTLIST libro tipo_clase CDATA #REQUIRED>
    <!ATTLIST libro paginas CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT capitulo (titulo,contenido)>
    <!ATTLIST capitulo paginas CDATA #REQUIRED>
<!ELEMENT contenido EMPTY>
    <!ATTLIST contenido enlace CDATA #REQUIRED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT indice (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>

=== Jose-ignacio-vazquez/lmsgiactividad2/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd" >
<biblioteca>
    <libros>
        <libro id="L1111" tipo_clase="novela" paginas="169">
            <titulo>
            </titulo>
            <capitulo paginas="32">
                <titulo></titulo>
                <contenido enlace="http://libro.com/capitulo1"></contenido>
                </capitulo>
                <capitulo paginas="43">
                    <titulo>
                    </titulo>
                    <contenido enlace="http://libro.com/capitulo2"></contenido>
                </capitulo>
                 <capitulo paginas="26">
                    <titulo>
                    </titulo>
                    <contenido enlace="http://libro.com/capitulo3"></contenido>
                </capitulo>
                <capitulo paginas="68">
                    <titulo>
                    </titulo>
                    <contenido enlace="http://libro.com/capitulo4"></contenido>
                </capitulo>               
            <indice>
            </indice>
            <sinopsis>
            </sinopsis>

            </libro>
            <libro id="L1112" tipo_clase="infantil">
            
            </libro>
            <libro id="didactico">
            
            </libro>
        </libros>
        
        <!--         REVISTAS           -->
        <revistas>
    
        </revistas>

        <!--        PERIODICOS          -->
        <periodicos>

        </periodicos>

</biblioteca>
